services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=demo-nodejs-jwt
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
      - frontend
  backend:
    depends_on:
      - db
    build: ./backend
    restart: always
    ports:
      # Host port:Container port
      - 3001:3001
    container_name: backend
    networks:
      - backend
  frontend:
    depends_on:
      backend:
        condition: service_completed_successfully
    build: ./frontend
    networks:
      - frontend
volumes:
  db:
networks:
  backend:
  frontend:
